# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

version: "3.3"
services:

  # Define api service and envoy sidecar proxy for version 2 of the service
  api_v2:
    # image: docker-build-fraud-sp:local
    # ports:
    #   - 8001:8001
    # cap_add:
    #   - SYS_NICE
    #   - NET_BIND_SERVICE
    image: nginx:alpine
    # ports:
    #   - 8080:27911
    volumes:
      - ./service_config/v2/index.html:/usr/share/nginx/html/index.html
      - ./service_config/default.conf.template:/etc/nginx/templates/default.conf.template:rw,cached
    environment:
      - NGINX_PORT=27911
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5


  api_proxy_v2:
    image: nicholasjackson/consul-envoy:v1.6.1-v0.10.0
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/api_v2.json
    volumes:
      - "./service_config:/config"
    command: ["consul", "connect", "envoy","-sidecar-for", "api-v2", "--", "-l", "debug", "--log-path", "envoy_logs.tx"]
    network_mode: "service:api_v2"


networks:
  vpcbr:
    external:
      name: fromcustomer_vpcbr
